/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PiscinasDeFibraRouteImport } from './routes/piscinas-de-fibra'
import { Route as PiscinaListaParaDisfrutarRouteImport } from './routes/piscina-lista-para-disfrutar'
import { Route as ObrasRouteImport } from './routes/obras'
import { Route as JacuzziSpaRouteImport } from './routes/jacuzzi-spa'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as ClimatizacionRouteImport } from './routes/climatizacion'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObrasObraIdRouteImport } from './routes/obras_.$obraId'

const PiscinasDeFibraRoute = PiscinasDeFibraRouteImport.update({
  id: '/piscinas-de-fibra',
  path: '/piscinas-de-fibra',
  getParentRoute: () => rootRouteImport,
} as any)
const PiscinaListaParaDisfrutarRoute =
  PiscinaListaParaDisfrutarRouteImport.update({
    id: '/piscina-lista-para-disfrutar',
    path: '/piscina-lista-para-disfrutar',
    getParentRoute: () => rootRouteImport,
  } as any)
const ObrasRoute = ObrasRouteImport.update({
  id: '/obras',
  path: '/obras',
  getParentRoute: () => rootRouteImport,
} as any)
const JacuzziSpaRoute = JacuzziSpaRouteImport.update({
  id: '/jacuzzi-spa',
  path: '/jacuzzi-spa',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const ClimatizacionRoute = ClimatizacionRouteImport.update({
  id: '/climatizacion',
  path: '/climatizacion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasObraIdRoute = ObrasObraIdRouteImport.update({
  id: '/obras_/$obraId',
  path: '/obras/$obraId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/climatizacion': typeof ClimatizacionRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/jacuzzi-spa': typeof JacuzziSpaRoute
  '/obras': typeof ObrasRoute
  '/piscina-lista-para-disfrutar': typeof PiscinaListaParaDisfrutarRoute
  '/piscinas-de-fibra': typeof PiscinasDeFibraRoute
  '/obras/$obraId': typeof ObrasObraIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/climatizacion': typeof ClimatizacionRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/jacuzzi-spa': typeof JacuzziSpaRoute
  '/obras': typeof ObrasRoute
  '/piscina-lista-para-disfrutar': typeof PiscinaListaParaDisfrutarRoute
  '/piscinas-de-fibra': typeof PiscinasDeFibraRoute
  '/obras/$obraId': typeof ObrasObraIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/climatizacion': typeof ClimatizacionRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/jacuzzi-spa': typeof JacuzziSpaRoute
  '/obras': typeof ObrasRoute
  '/piscina-lista-para-disfrutar': typeof PiscinaListaParaDisfrutarRoute
  '/piscinas-de-fibra': typeof PiscinasDeFibraRoute
  '/obras_/$obraId': typeof ObrasObraIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/climatizacion'
    | '/diagnostico'
    | '/jacuzzi-spa'
    | '/obras'
    | '/piscina-lista-para-disfrutar'
    | '/piscinas-de-fibra'
    | '/obras/$obraId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/climatizacion'
    | '/diagnostico'
    | '/jacuzzi-spa'
    | '/obras'
    | '/piscina-lista-para-disfrutar'
    | '/piscinas-de-fibra'
    | '/obras/$obraId'
  id:
    | '__root__'
    | '/'
    | '/climatizacion'
    | '/diagnostico'
    | '/jacuzzi-spa'
    | '/obras'
    | '/piscina-lista-para-disfrutar'
    | '/piscinas-de-fibra'
    | '/obras_/$obraId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClimatizacionRoute: typeof ClimatizacionRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  JacuzziSpaRoute: typeof JacuzziSpaRoute
  ObrasRoute: typeof ObrasRoute
  PiscinaListaParaDisfrutarRoute: typeof PiscinaListaParaDisfrutarRoute
  PiscinasDeFibraRoute: typeof PiscinasDeFibraRoute
  ObrasObraIdRoute: typeof ObrasObraIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/piscinas-de-fibra': {
      id: '/piscinas-de-fibra'
      path: '/piscinas-de-fibra'
      fullPath: '/piscinas-de-fibra'
      preLoaderRoute: typeof PiscinasDeFibraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piscina-lista-para-disfrutar': {
      id: '/piscina-lista-para-disfrutar'
      path: '/piscina-lista-para-disfrutar'
      fullPath: '/piscina-lista-para-disfrutar'
      preLoaderRoute: typeof PiscinaListaParaDisfrutarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras': {
      id: '/obras'
      path: '/obras'
      fullPath: '/obras'
      preLoaderRoute: typeof ObrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jacuzzi-spa': {
      id: '/jacuzzi-spa'
      path: '/jacuzzi-spa'
      fullPath: '/jacuzzi-spa'
      preLoaderRoute: typeof JacuzziSpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/climatizacion': {
      id: '/climatizacion'
      path: '/climatizacion'
      fullPath: '/climatizacion'
      preLoaderRoute: typeof ClimatizacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras_/$obraId': {
      id: '/obras_/$obraId'
      path: '/obras/$obraId'
      fullPath: '/obras/$obraId'
      preLoaderRoute: typeof ObrasObraIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClimatizacionRoute: ClimatizacionRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  JacuzziSpaRoute: JacuzziSpaRoute,
  ObrasRoute: ObrasRoute,
  PiscinaListaParaDisfrutarRoute: PiscinaListaParaDisfrutarRoute,
  PiscinasDeFibraRoute: PiscinasDeFibraRoute,
  ObrasObraIdRoute: ObrasObraIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
